upload:
  # 文件服务域名
  domain: http://localhost:${server.port}/
  #  domain: http://xxxxxxxxx.hn-bkt.clouddn.com
  # 本地资源目录
  local-path: tmp/
  # 服务器资源目录
  server-path: tmp/**
  # 每次上传文件的最大数量
  count: 9
  # 支持的文件扩展名
  whitelist:
    - .jpg
    - .png

spring:
  servlet:
    multipart:
      # 每次上传文件的大小
      max-file-size: 2MB
      # 每次上传文件的总大小
      max-request-size: 10MB

qiniu:
  access-key:
  secret-key:
  bucket: