# 主配置文件

spring:
  # 激活配置
  profiles:
    active: dev
  mvc:
    # 404 交给异常处理
    throw-exception-if-no-handler-found: true

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel_case: true
    # 指定默认枚举类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  # mapper xml路径
  mapper-locations: classpath:mapper/*.xml