# 主配置文件

spring:
  # 激活配置
  profiles:
    active: dev
  # 文件编码格式
  mandatory-file-encoding: UTF-8
  mvc:
    # 404 交给异常处理
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭默认静态资源的映射规则
      # springboot中，404异常是进行了默认资源映射的，
      # 如果没有做特殊配置，我们的异常处理系统就会处理不到404请求
      add-mappings: false

cappuccino:
  api-path: com.blcheung.cappuccino.controller
  # cms配置
  cms:
    # 秘钥
    secret: 123456789
    # token过期时长，默认一天
    access-token-expired: 86400
    # refresh_token过期时长，默认604800s 一周
    refresh-token-expired: 604800

  # 宫格最大数量
  grid-category-maximum: 6

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel_case: true
    # 指定默认枚举类型转换器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
    db-config:
      # 逻辑删除（软删除）
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  # mapper xml路径
  mapper-locations: classpath:mapper/*.xml